#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Telegram Project — AWS EC2 Deployment Script
# Run this from your LOCAL machine (macOS) from the telegram/ project root.
# ============================================================================

EC2_HOST="ec2-16-176-50-201.ap-southeast-2.compute.amazonaws.com"
EC2_USER="ubuntu"
EC2_IP="16.176.50.201"
PEM_KEY="./new key.pem"
REMOTE_DIR="/home/ubuntu/telegram"
SSH_OPTS="-o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=5"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[DEPLOY]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

ssh_cmd() {
  ssh $SSH_OPTS -i "$PEM_KEY" "${EC2_USER}@${EC2_HOST}" "$@"
}

# ── Pre-flight checks ──────────────────────────────────────────────────────
[ -f "$PEM_KEY" ] || err "PEM key not found at '$PEM_KEY'. Run this script from the telegram/ project root."
chmod 400 "$PEM_KEY"

log "Testing SSH connection to ${EC2_HOST}..."
ssh_cmd "echo 'SSH OK'" || err "Cannot SSH into EC2. Check Security Group allows port 22 from your IP."

# ── Step 1: Install Docker & Docker Compose on EC2 ─────────────────────────
log "Step 1/4: Installing Docker on EC2..."
ssh_cmd 'bash -s' << 'INSTALL_DOCKER'
set -euo pipefail

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
  echo "Docker already installed: $(docker --version)"
  echo "Docker Compose: $(docker compose version)"
  exit 0
fi

echo "Installing Docker..."
sudo apt-get update -y
sudo apt-get install -y ca-certificates curl gnupg lsb-release

sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo usermod -aG docker ubuntu
echo "Docker installed: $(docker --version)"
echo "Docker Compose: $(docker compose version)"
INSTALL_DOCKER

# ── Step 2: Upload project to EC2 ──────────────────────────────────────────
log "Step 2/4: Syncing project to EC2 (this may take a few minutes)..."
rsync -avz --progress \
  -e "ssh $SSH_OPTS -i \"$PEM_KEY\"" \
  --exclude='node_modules' \
  --exclude='.turbo' \
  --exclude='.pnpm-store' \
  --exclude='dist' \
  --exclude='apps/**/build' \
  --exclude='packages/**/build' \
  --exclude='.DS_Store' \
  --exclude='.env' \
  --exclude='.env.*' \
  --exclude='coverage' \
  --exclude='.expo' \
  --exclude='.expo-shared' \
  --exclude='ios/build' \
  --exclude='ios/Pods' \
  --exclude='android/.gradle' \
  --exclude='android/app/build' \
  --exclude='tmp' \
  --exclude='.git' \
  --exclude='apps/mobile-ios/vendor' \
  --exclude='apps/mobile-ios/ios/Pods' \
  --exclude='apps/mobile-ios/ios/build' \
  --exclude='*.pem' \
  --exclude='deploy-aws.sh' \
  ./ "${EC2_USER}@${EC2_HOST}:${REMOTE_DIR}/"

# ── Step 3: Create .env file with EC2 public IP ────────────────────────────
log "Step 3/4: Configuring environment with public IP ${EC2_IP}..."
ssh_cmd "cat > ${REMOTE_DIR}/infra/docker/.env" << ENVFILE
# === Auto-generated by deploy-aws.sh ===
# EC2 Public IP
LOCAL_DEV_HOST=${EC2_IP}
TURN_EXTERNAL_HOST=${EC2_IP}

# Security (change these for production!)
JWT_ACCESS_SECRET=production-jwt-secret-$(openssl rand -hex 16)
TURN_SHARED_SECRET=production-turn-secret-$(openssl rand -hex 16)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

# MinIO
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=minioadmin
MINIO_DEFAULT_BUCKET=telegram-media

# Calls
CALLS_V1_ENABLED=true

# Push notifications (dry_run = no actual push)
VOIP_PROVIDER_MODE=dry_run
PUSH_PROVIDER_MODE=dry_run
FCM_PROVIDER_MODE=disabled
ENVFILE

# ── Step 4: Build & Start containers ───────────────────────────────────────
log "Step 4/4: Building and starting Docker containers (this will take 5-10 minutes on first run)..."
ssh_cmd "bash -s" << 'START_DOCKER'
set -euo pipefail
cd /home/ubuntu/telegram/infra/docker

# Make sure we can use docker without sudo (newgrp in non-interactive shell)
if ! docker info &>/dev/null 2>&1; then
  sudo docker compose up -d --build
  echo "STARTED_WITH_SUDO"
else
  docker compose up -d --build
  echo "STARTED"
fi
START_DOCKER

# ── Done ────────────────────────────────────────────────────────────────────
log "=========================================="
log "  DEPLOYMENT COMPLETE!"
log "=========================================="
echo ""
echo "  API Gateway:     http://${EC2_IP}:3000"
echo "  Call Signaling:   http://${EC2_IP}:3007/calls"
echo "  STUN/TURN:        ${EC2_IP}:3478"
echo "  RabbitMQ Console: http://${EC2_IP}:15672 (guest/guest)"
echo "  MinIO Console:    http://${EC2_IP}:9001 (minio/minioadmin)"
echo ""
echo "  Update your mobile app env.ts:"
echo "    const PROD_HOST = '${EC2_IP}';"
echo ""
log "To check logs:  ssh -i \"${PEM_KEY}\" ${EC2_USER}@${EC2_HOST} 'cd ${REMOTE_DIR}/infra/docker && docker compose logs -f'"
log "To stop:        ssh -i \"${PEM_KEY}\" ${EC2_USER}@${EC2_HOST} 'cd ${REMOTE_DIR}/infra/docker && docker compose down'"
